# configuration file for slurm
executor: slurm
jobs: 400
slurm-logdir: "/data/smew01/not-backed-up/tagami/snakemake-quantitative-trait-simulation/snakemake-log"

default-resources:
    slurm_account: "tagami"
    slurm_partition: "standard-statgen-cpu"
    cpus_per_task: 1
    mem_mb: 40000
    runtime: "20h"
    slurm_extra: "--nodelist=smew01.cpu.stats.ox.ac.uk"
