# Causal mutation rate per site
mu: 1e-10

# Gamma distribution parameters for simulating population-scaled
# mutation size
# Shape of Gamma distribution
shape: 1
# Scale of Gamma distribution
scale: 10
# Population size of population-scaled mutation size
N: 1e4
# Parameter of stabilizing selection model (w)
w: 1

# Filename of recombination map in "recombination_map" directory
# This should be a number to specify the chromosome number in
# recombination map file
chromosome: 
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
# Filename of JSON demography file in "demography" directory
# Do not add ".json" suffix to filename
demography: "demography"
# SLiM simulation seed
slim_seed: 1

# Degree of pleiotropic effects
degree: 100
# Effect size simulation seed
effect_size_seed: 2

# Narrow-sense heritability
h2: 0.4
# Phenotype simulation seed
phenotype_seed: 3

# Neutral mutation rate
neutral_mu: 1e-8
# Ancestral Ne
ancestral_Ne: 3600
# Seed for recapitation
recapitate_seed: 4
# Neutral simulation and recapitation seed
neutral_seed: 5

# These parameters are important for simulations
# but they do not need to be modified

# Scaling for selection coefficient to conduct underdominance
# selection simulation
scaling_selection: 1e10