# Causal mutation rate per site
mu: 1e-10

# Gamma distribution parameters for simulating population-scaled
# mutation size
# Shape of Gamma distribution
shape: 0.19
# Scale of Gamma distribution
scale: 0.0741
# Parameter of stabilizing selection model (w)
w: 1

# Filename of recombination map in "recombination_map" directory
# This should be a number to specify the chromosome number in
# recombination map file
chromosome:
  - 1
# Filename of JSON demography file in "demography" directory
# Do not add ".json" suffix to filename
demography: "demography_4M"
# SLiM simulation seed
slim_seed: 1000

# Degree of pleiotropic effects
degree: 100
# Effect size simulation seed
effect_size_seed: 1

# Narrow-sense heritability
h2: 0.4
# Phenotype simulation seed
phenotype_seed: 3

# Neutral mutation rate
neutral_mu: 1e-8
# Ancestral Ne
ancestral_Ne: 3600
# Seed for recapitation
recapitate_seed: 4
# Neutral simulation and recapitation seed
neutral_seed: 5

# Number of YRI individuals:
YRI_number: 30000
# Number of CEU individuals:
CEU_number: 340000
# Seed to select individual IDs:
individual_seed: 2

# MAF threshold
MAF: 0.0005

# These parameters are important for simulations
# but they do not need to be modified

# Scaling for selection coefficient to conduct underdominance
# selection simulation
scaling_selection: 1e10